name = "Russian Ukraine Insignias";
picture = "SCORPIO4938_\RussianUkraineInsignia\data\ru.paa";           // 如果有logo.paa可以填路径
logo = "SCORPIO4938_\RussianUkraineInsignia\data\ru.paa";
logoOver = "SCORPIO4938_\RussianUkraineInsignia\data\ru.paa";
actionName = "GitHub";
action = "";
tooltip = "Custom Russian Ukraine Insignias";
tooltipOwned = "Custom Russian Ukraine Insignias Mod";
overview = "Add Custom Russian Ukraine Insignias";
author = "Scorpio493.8";